### ISSUE TITLE
Support for creating encrypted 7z & zip archives

### ISSUE THREAD

**Issue by tmyroadctfig** [borisbrodski/sevenzipjbinding#10]
Is it possible to create a 7z or zip archive with a password to protect the items in the archive? There are currently methods for extracting password protected content, but I can't see any equivalents for creating protected archives.

Thanks, Luke

**Comment by borisbrodski** [comment]
Hello Luke,

sorry, this is very well possible with 7-Zip API, but it's not implemented in 7-Zip-JBinding yet.

Cheers,
Boris

**Comment by borisbrodski** [comment]
It is implemented now. Release 16.02-2.01.
