### ISSUE TITLE
RAR5 support

### ISSUE THREAD

**Issue by Mgamerz** [borisbrodski/sevenzipjbinding#19]
I'm curious if the 16.02 version you have in beta supports RAR5?

I have to open files made by other users that I have absolutely no control over. For the most part I haven't seen RAR5 archives come in, but once in a while they do and it just goes belly up. Wondering if there is support for this in 16.02 as it would be very helpful to mitigate this.

I use application as a pretty integral part of my app, used by tens of thousands of users. Was nice to use to make it easier for users to use my app rather than have to do manual extraction.

**Comment by optyfr** [comment]
Hello, I tried this unofficial one [here](https://sourceforge.net/projects/sevenzipjbind/files/OldFiles/JDownloader-16.02-2.01beta-try1/sevenzipjbinding-16.02-2.01beta-AllPlatforms.zip/download) and was able to uncompress RAR5

**Comment by borisbrodski** [comment]
Version 16.02 (with non-beta release) will support RAR5. It will be released on 19.02.2020.
