### ISSUE TITLE
Android library version

### ISSUE THREAD

**Issue by omicronapps** [borisbrodski/sevenzipjbinding#23]
FYI. Complete Android port of 7-Zip-JBinding available at [7-Zip-JBinding-4Android](https://github.com/omicronapps/7-Zip-JBinding-4Android). This is a Gradle / Android Studio project setup of the v9.20-2.00beta release from SourceForge. Includes the original unit test framework.
Note: not a proper fork of sevenzipjbinding, as I wanted to keep porting efforts simple from a published complete release.

**Comment by borisbrodski** [comment]
Hello Fredrik,

it looks fantastic :) Nice job!

I will add your link to 7-Zip-JBinding web page. I also encourage you to write to Igor Pavlov. He can add your project to the official list at https://www.7-zip.org/links.html

Android support is a fat bullet on my TODO list. So I'm very happy, it exists now. Do you plan to upload your release to the Maven Central or JCenter?

Currently I'm finishing testing the upcoming release supporting a variety of ARM-architectures (5, 6, 7 and 64). Also binding 7-Zip 16.02 :)

Should we somehow coordinate our efforts?


PS
It would be cool if you could add a small example, how to add 7-Zip-JBinding-4Android to an Android-project. Just for newbies.

**Comment by omicronapps** [comment]
Hi Boris,

Thanks! I was looking for a 7z-archiver for Android, and figured 7-Zip-JBinding could be a good porting candidate with a little bit of work.

Porting SevenZip itself was quite straightforward, and primarily required creating a CMake setup suitable for Android and to replace the JAR-based loading mechanism of the native library with an Android-style loadLibrary() System call.

However the major part of the work was trying to get the unit tests to work, which proved to be a bit of a challenge with all the hard-coded filesystem calls, which are not compatible with Android. There are still some unit tests that fail, either due to GC issues, invalid local JNI references, or missing test archives. Some unit tests seem to result in a lot of Java objects being retained and/or temporary files being created. I tagged some unit tests with Ignore, while others will fail. Most pass however, so I think the Android library version overall is in pretty good shape.

Thanks for the suggestions. I updated the [README.md](https://github.com/omicronapps/7-Zip-JBinding-4Android/blob/master/README.md) with instructions for how to build and include the AAR library in an Android Studio / Gradle project, along with some examples of using the library. But the library can be used exactly as described in the 7-Zip-JBinding documentation, so any user of the Android library should be able to refer to that directly for more advanced operations.

Yes, I should look at uploading to Maven Central and/or JCenter, so that's on the TODO.

Please feel free to link [7-Zip-JBinding-4Android](https://github.com/omicronapps/7-Zip-JBinding-4Android) to the [7-Zip-JBinding](http://sevenzipjbind.sourceforge.net/) web page, thanks! Will reach out Igor Pavlov as well.

Sounds like a good idea to coordinate efforts for the upcoming release. Some abstraction interfaces for loading the native library and accessing local and temporary files for unit testing would be good, I think.

/Fredrik

**Comment by omicronapps** [comment]
@borisbrodski Updated [7-Zip-JBinding-4Android](https://github.com/omicronapps/7-Zip-JBinding-4Android). Turns out the initial implementation did not properly support JNI access from native threads. Specifically, Java object access from the native thread requires a global reference before attaching. Also, finding classes from the native thread requires a work-around on Android, since the ClassLoader is not directly available in the native thread. In addition, also added `__ANDROID_API__` pre-processor macros to help identify Android specific code.
Commit [a88f5403814a86e0d2d85937c13ff8b1c058ab9f](https://github.com/omicronapps/7-Zip-JBinding-4Android/commit/a88f5403814a86e0d2d85937c13ff8b1c058ab9f) includes the above changes.

**Comment by omicronapps** [comment]
@borisbrodski Cleaned up [7-Zip-JBinding-4Android](https://github.com/omicronapps/7-Zip-JBinding-4Android) further. Specifically, added back all of the original generic Java code, and using `java.vendor` System property to enable Android specific code paths (not ideal, but no conditional pre-processor equivalents in Java, as you know). In addition, also removed several Ignore annotations now that these are redundant with the previous changes, resulting in a nearly completely passing unit test coverage.
Note that JAR resources "sevenzipjbinding-platforms.properties", "sevenzipjbinding-lib.properties", and "MANIFEST.MF" are include as hardcoded Strings for Android, since including them as assets in the AAR will require access to the Context for the AAR, which would require altering the original 7-Zip-JBinding API. I think this is a reasonable compromise, but let me know if you disagree with this.
Commit [f611f7568e892cdb256825ecfb21b24e67bb2573](https://github.com/omicronapps/7-Zip-JBinding-4Android/commit/f611f7568e892cdb256825ecfb21b24e67bb2573) includes the above changes.

**Comment by omicronapps** [comment]
Merged over commit [9e1206a2fe0d526bc3a9d9b3039ca15fa7b6b99b](https://github.com/borisbrodski/sevenzipjbinding/commit/9e1206a2fe0d526bc3a9d9b3039ca15fa7b6b99b) of [sevenzipjbinding](https://github.com/borisbrodski/sevenzipjbinding) to [7-Zip-JBinding-4Android](https://github.com/omicronapps/7-Zip-JBinding-4Android) here: [efdc5b9c9e8ecba5a80ff7c942ae165f554cbeba](https://github.com/omicronapps/7-Zip-JBinding-4Android/commit/efdc5b9c9e8ecba5a80ff7c942ae165f554cbeba).

Unit test status:
> Tests failed: 791, passed: 7620 of 8411 tests

Most failures are due to missing files, so suspect some further tweaks are required to the test framework (which has typically been the case so far for unit test case failures), but the library itself should be fully functional.

Noted that some more recent [commits](https://github.com/borisbrodski/sevenzipjbinding/commits/master) have been made the last couple of days, so should look into merging these into [7-Zip-JBinding-4Android](https://github.com/omicronapps/7-Zip-JBinding-4Android) as well.

**Comment by Nillouise** [comment]
awsome, It there a new release plan?

**Comment by omicronapps** [comment]
Thanks for the reminder. Just merged the latest changes from [sevenzipjbinding](https://github.com/borisbrodski/sevenzipjbinding) and released [Release-16.02-2.01](https://github.com/omicronapps/7-Zip-JBinding-4Android/releases/tag/Release-16.02-2.01) of [7-Zip-JBinding-4Android](https://github.com/omicronapps/7-Zip-JBinding-4Android).
