### ISSUE TITLE
Password protected rar file extraction

### ISSUE THREAD

**Issue by qqli007** [borisbrodski/sevenzipjbinding#3]
Is it support password-protected rar file?

**Comment by borisbrodski** [comment]
Yes. You have to either

* Implement ICryptoGetTextPassword: http://sevenzipjbind.sourceforge.net/javadoc/net/sf/sevenzipjbinding/ICryptoGetTextPassword.html
```java
class MyExtractCallback implements IArchiveExtractCallback, ICryptoGetTextPassword {...}
```
* or use extractSlow() method with "password" parameter: [link](http://sevenzipjbind.sourceforge.net/javadoc/net/sf/sevenzipjbinding/IInArchive.html#extractSlow(int, net.sf.sevenzipjbinding.ISequentialOutStream, java.lang.String))

**Comment by borisbrodski** [comment]
Please, reopen this issue, if you have any problems with password protected RAR archives.

**Comment by jeytin** [comment]
How check  rar file  exists   password ?  
if  exists,  show dialog input  ?

**Comment by borisbrodski** [comment]
You have to try to extract the file. If it works, there is no password and you can stop the extraction by throwing an exception.

**Comment by jeytin** [comment]
Thank you,  let me try .
