### ISSUE TITLE
RandomAccessFileOutStream class is better to implement the java.io.Closeable intarface.

### ISSUE THREAD

**Issue by yososs** [borisbrodski/sevenzipjbinding#5]
RandomAccessFileOutStream class is better to implement the java.io.Closeable intarface. Easily it will be able to close in the utility methods such as IOUtils.closeQuietly () in doing so.

In RandomAccessFileInStream Closeable it has been implemented.

**Comment by borisbrodski** [comment]
Thank you! I will add it.

**Comment by faisal8048003** [comment]
![IMG_20220121_235248_678](https://user-images.githubusercontent.com/56052048/150663671-b0e6c83a-b4c3-46fb-b03f-b49255597f58.jpg) #47
