### ISSUE TITLE
Unable to extract gzip & bzip2 files- Android

### ISSUE THREAD

**Issue by asthagarg2428** [borisbrodski/sevenzipjbinding#52]
I'm using this library in my Android Application and I'm unable to extract gzip, bzip2 files

The same code is working fine for zip, 7zip, tar but I'm unable to extract gzip, bzip2 file.
While debugging it, I found that the data corresponding to each child item in the archive file(gzip & bzip2) is blank.

`inArchive.getStringProperty(i, PropID.IS_FOLDER)` is  `""`
`inArchive.getStringProperty(i, PropID.PATH)` is `""`

Waiting for your response

Thanks.

**Comment by borisbrodski** [comment]
Glad it's worked out.

**Comment by MyAndyMy** [comment]
How your code work fine on extracting .7z file on Android?
I am confused on #4
