### ISSUE TITLE
Do you need a version up to 7zip v16?

### ISSUE THREAD

**Issue by yososs** [borisbrodski/sevenzipjbinding#6]
Two vulnerabilities in 7zip have been reported in this article.
- [Multiple 7-Zip Vulnerabilities Discovered by Talos](http://blog.talosintel.com/2016/05/multiple-7-zip-vulnerabilities.html)

**Comment by borisbrodski** [comment]
Thank you for the Link. I will look into the issues.

**Comment by borisbrodski** [comment]
Thank you again!

I will port 7-Zip-JBinding to version 16.02 as soon as possible.

**Comment by borisbrodski** [comment]
16.02 will be released on 19.02.2020.
