### ISSUE TITLE
Get sources for sevenzipjbinding-all-platforms

### ISSUE THREAD

**Issue by rajaveld** [borisbrodski/sevenzipjbinding#67]
We are using https://mvnrepository.com/artifact/net.sf.sevenzipjbinding/sevenzipjbinding-all-platforms/9.20-2.00beta

Since sevenzipjbinding-all-platforms:9.20-2.00beta LGPL 2.1, I like to know the sources for this binary.

In Maven repo also I could not fine the sources.  Could you please redirect to place where I can find the sources for this.

**Comment by borisbrodski** [comment]
Thank you for using 7-Zip-JBinding.
Your issue is created in the GitHub repository with the entire source code and all build scripts necessary to build the libraray yourself.

https://github.com/borisbrodski/sevenzipjbinding/

**Comment by rajaveld** [comment]
Thanks
