### ISSUE TITLE
net.sf.sevenzipjbinding.SevenZip#byteArrayToHex incorrect implementation.

### ISSUE THREAD

**Issue by kopavel** [borisbrodski/sevenzipjbinding#71]
method net.sf.sevenzipjbinding.SevenZip#byteArrayToHex are implement incorrectly.
Integer.toHexString(0xFF & byteArray[i]) lost leading zeroes (return 'a' instead of '0a' for  byte '0x0a')
as rezult HASH always mismatch and LIB always try rewrite jna DLL and fail to do this if I redeploy WAR (old instance hold DLL and process can't access to it).
Correct way to do this is using String.format("%02X", 0xFF & byteArray[i]);

**Comment by kopavel** [comment]
it seems copy #31 but no official release from this time :(

**Comment by borisbrodski** [comment]
I'm working on it
